// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayrollEngine.Infrastructure;

#nullable disable

namespace PayrollEngine.Infrastructure.Migrations
{
    [DbContext(typeof(PayrollEngineDbContext))]
    [Migration("20260208164902_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PayrollEngine.Domain.Entities.ActiveSSParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmployeeSSRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmployeeUIRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmployerSSRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmployerUIRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActiveSSParams");
                });

            modelBuilder.Entity("PayrollEngine.Domain.Entities.CumulativeIncomeTaxBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CumulativeBase")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Month")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CumulativeIncomeTaxBases");
                });

            modelBuilder.Entity("PayrollEngine.Domain.Entities.EmployeeScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisabilityDegree")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncentiveType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PayType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalaryInputType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EmployeeScenarios");
                });

            modelBuilder.Entity("PayrollEngine.Domain.Entities.IncomeTaxBracket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Bracket")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IncomeTaxBrackets");
                });

            modelBuilder.Entity("PayrollEngine.Domain.Entities.MinimumWage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MinimumWages");
                });

            modelBuilder.Entity("PayrollEngine.Domain.Entities.PayrollMonth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BonusAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Overtime100")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Overtime50")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrivateHealthInsurance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShoppingVoucher")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WorkDay")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PayrollMonths");
                });

            modelBuilder.Entity("PayrollEngine.Domain.Entities.PayrollTemplateMonth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BonusAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Overtime100")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Overtime50")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrivateHealthInsurance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalaryIncreaseRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShoppingVoucher")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WorkDay")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PayrollTemplateMonths");
                });

            modelBuilder.Entity("PayrollEngine.Domain.Entities.ResultPayroll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BonusAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CumulativeIncomeTaxBase")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmployeeSSContributionAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmployeeUIContributionAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmployerSSContributionAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmployerUIContributionAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IncentiveDiscount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IncomeTax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IncomeTaxBase")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IncomeTaxExemption")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Overtime100Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Overtime50Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrivateHealthInsurance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SSContributionBase")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SSDay")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShoppingVoucher")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StampTax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StampTaxExemption")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalEmployerCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalSalary")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WorkDay")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ResultPayrolls");
                });

            modelBuilder.Entity("PayrollEngine.Domain.Entities.RetiredSSParams", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmployeeSSRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EmployerSSRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RetiredSSParams");
                });

            modelBuilder.Entity("PayrollEngine.Domain.Entities.SSCeiling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ceiling")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SSCeilings");
                });

            modelBuilder.Entity("PayrollEngine.Domain.Entities.StampTax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Year")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StampTaxes");
                });
#pragma warning restore 612, 618
        }
    }
}
